### ISSUE TITLE
Invalid request body when running the first time the package. 

### ISSUE THREAD

**Issue by ben55j** [joshnuss/svelte-stripe#103] opened 2024-01-10 21:28 UTC
### Describe the bug

Hello, 

After cloning the package, and running as described with the command line: `pnpm dev`, 

The server starts on the URL : https://localhost:5173/

But when I open it, the message: "Invalid request body" along with the not secured flag next to the URL. 
I cannot figure out how to run it properly. 

<img width="541" alt="Capture d’écran 2024-01-10 à 22 16 16" src="https://github.com/joshnuss/svelte-stripe/assets/7754473/3e07698a-5d4a-405a-9141-a3f6573319fb">

Please help, 
Many thanks, 

Benjamin

### Reproduction

1.   Clone the project: `git clone https://github.com/joshnuss/svelte-stripe.git`
2.  And the .env file to the root with the PUBLIC_STRIPE_KEY and SECRET_STRIPE_KEY
3. Run `pnpm dev`,
4. Go to https://localhost:5173/

### Severity

annoyance

**Comment by joshnuss** [comment] 2024-01-10 21:36
Are you trying to run the development version?

The security warning is expected, because it's using `https://` with `localhost`, but the SSL certificate is generated (not from an official authority)

What browser are you using?
What do the server logs show?
Have you tried using the browser devtools? Do you see any errors there? HTTP status code?

**Comment by ben55j** [comment] 2024-01-10 22:26
Hello Joshnuss!

- Yes , I am trying to run the development version using `pnpm dev`
- I have the issue on both Chome and Safari
- On Chrome the devtools only gives the following clues
<img width="832" alt="Capture d’écran 2024-01-10 à 23 18 33" src="https://github.com/joshnuss/svelte-stripe/assets/7754473/52931394-da9a-4bfb-855c-73b64e3d71f7">

**Comment by joshnuss** [comment] 2024-01-10 22:51
Those logs are definitely not from this project. That's odd.

That will help us determine if the issue is on the server side or browser side,

In a terminal, can you try `curl --insecure https://localhost:5173`?

**Comment by ben55j** [comment] 2024-01-11 06:35
Here is the output off the command: 
`Invalid request body%  
`
![image](https://github.com/joshnuss/svelte-stripe/assets/7754473/4e047ddc-1655-48f8-b499-83dda0c828c6)

**Comment by joshnuss** [comment] 2024-01-11 07:02
It's working fine for me.

What package versions are you running?

```sh
pnpm list
```

Have you made any local modifications?
Can you reproduce this in Stackblitz? (just don't include your Stripe private keys)
Have you configured a `.env.development`?

**Comment by joshnuss** [comment] 2024-01-11 07:14
Tested it with GitHub CodeSpaces and it's loading fine.

It must be something with your setup.

**Comment by ben55j** [comment] 2024-01-11 10:27
Okay I'll investigate and let you know. Thanks for your help

**Comment by ben55j** [comment] 2024-01-11 17:56
Hello,, here is the result with `pnpm list`: 

<img width="843" alt="Capture d’écran 2024-01-11 à 18 53 18" src="https://github.com/joshnuss/svelte-stripe/assets/7754473/5380a6b9-a7b8-4649-b9a9-008523de6d39">

Regarding the .env.development , I have only created a new .env file with both SECRET_STRIPE_KEY @ PUBLIC_STRIPE_KEY.

**Comment by joshnuss** [comment] 2024-01-31 03:24
Have you tried opening the repo with GitHub CodeSpaces?

Or can you provide a repo with a minimal reproduction? Cause I'm not seeing this error, and using similar package versions to those you've listed.

**Comment by joshnuss** [comment] 2024-04-19 01:04
Closing as unable to reproduce and not being reported by anyone else.
Please re-open if you have a minimal reproduction.

**Closed by joshnuss** 2024-04-19 01:04 UTC
